### ISSUE TITLE
implement variable binding for voting variables (s to voter_counter)

### ISSUE THREAD

**Issue by Bumboclaat** [isse-augsburg/minibrass#14]

**Comment by Alexander-Schiendorfer** [comment]
```
//TODO deref would be better
String genName = first.getName() + "_MBR_LEX_" +(++productCounter) + next.getName(); 
```
inject derefed names on second pass

**Comment by Bumboclaat** [comment]
imlement "bind to.." for pareto and lex

**Comment by Alexander-Schiendorfer** [comment]
We leave this aside for the moment. If we want to use the bind-feature, we need to have a voting instance. 
So, we would replace `solve a lex (b pareto c)` by `solve vote([a,b pareto c], lex)` to indicate that only the highest level refers to the voters (so a single voter can add pareto/lex products)
