### ISSUE TITLE
soft_contraints/constraint_relationship_search.mzn not found

### ISSUE THREAD

**Issue by ChSt** [isse-augsburg/minibrass#8]
After installing minibrass using the minisearch variant, I get the error message:
"Error: cannot open file 'soft_constrains/constraint_relationship_search.mzn'."

This file is called from "minisearch_bundle.mzn" and should be included in "soft-constraints.zip" from http://www.isse.uni-augsburg.de/software/minibrass/. Unfortunately, I also could not find the file in the repository.

**Comment by Alexander-Schiendorfer** [comment]
Thank you for pointing that out!

The HelloWorld has been quite deprecated - there is a new version online, please give it a try.
